### ISSUE TITLE
How do I import/export a template once it's made? 

### ISSUE THREAD

**Issue by guilamu** [SendWithSES/Drag-and-Drop-Email-Designer#2]
Hello,

Thanks  a lot for your work. How do I import/export a template once it's made?

Bests,

**Comment by yeleti** [comment]
**To Export:** Click on the "Export HTML" button. You can copy the code from here.

**To Import:** Choose "HTML Editor" and copy-paste your code.

**Comment by guilamu** [comment]
Thanks for your reply!

When I do what you suggested, I can see my email, but I cannot edit anymore in the designer.

**Comment by yeleti** [comment]
Can you elaborate please? And if possible can you send a screen recording of what you are trying to do?

**Comment by guilamu** [comment]
Sure: https://youtu.be/AgxNbvB2A9s
