### ISSUE TITLE
Dependency Error Installing Drag-and-Drop-Email-Designer 

### ISSUE THREAD

**Issue by CBlakeB** [SendWithSES/Drag-and-Drop-Email-Designer#5]
I really like the live demo and I want to install on my local Linux Mint computer. I first installed NPM from https://nodejs.org. I then tried to run the install from a terminal using.

npm install @send-with-ses/ng-email-designer

I then received dependency errors. Like:
11 verbose stack Error: unable to resolve dependency tree
111 verbose stack     at #failPeerConflict (/home/blake/.nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1360:25)

I am attaching the full log file. 
[2024-09-08T17_48_16_843Z-debug-0.log](https://github.com/user-attachments/files/16923252/2024-09-08T17_48_16_843Z-debug-0.log)

Thanks,
Blake

**Comment by yeleti** [comment]
npm install @send-with-ses/ng-email-designer --force

try this approach and let me know how it goes.
