### ISSUE TITLE
Hi Kishore

### ISSUE THREAD

**Issue by Kikovenu** [SendWithSES/Drag-and-Drop-Email-Designer#7]
Hi Kishor,

How are you doing?

This is Venu from Portland, OR, USA but originally from Guntur, AP. We're facing issues implementing this editor, as we're using Angular 18, Bootstrap, and .NET 8. Could you please help us out?

Best regards, Venu & Sekhar

**Comment by Kikovenu** [comment]
![image](https://github.com/user-attachments/assets/6a9f40b0-dbd2-4d6a-9a9e-81a9cf5a778c)

Please review, the designer is not loading

**Comment by nkishorchandra** [comment]
Hi Venu, 
Thanks for showing interest in our email designer.

Could you please share the part of the code how you integrated into your app ?

Also, did you add any elements to the template before export ? or was it just blank ?

**Comment by Kikovenu** [comment]
Hi Kishor,

Thank you for your support. Sekhar will be sharing the code details with you. Would it be possible to schedule a Zoom call to discuss and demonstrate the issues we're facing? I'm in the PST time zone (California). Please let me know what works for you. You can reach me at i@venuganga.com.

Best regards,
Venu

**Comment by Kikovenu** [comment]
Hi Kishor,

How are you doing?
Please respond when you see this message. We need your help in fixing the issue.

Best regards
Venu & Sekhar

**Comment by nkishorchandra** [comment]
Hi kikovenu,
was away on a vacation, hence delay in reply. I'll check this today and get back.

**Comment by nkishorchandra** [comment]
@Kikovenu, 
please include 'scripthost' in lib of tsconfig.json

    ```
    "lib": [
          "es2018",
          "dom",
          "ScriptHost"
        ],
    ```

that should solve the 'ActiveXObject' issue.

**Comment by Kikovenu** [comment]
Thank you,
We will let you know once we test it
